name: clean_flutter_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  intl: 0.16.1
  logger: ^0.9.4
  hive: ^1.4.4+1
  provider: ^4.3.2+2
  enum_to_string: ^1.0.14
  path_provider: ^1.6.24
  json_serializable: ^3.5.1
  rxdart: ^0.24.1

  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  domain:
    path: ./domain

  cupertino_icons: ^1.0.0

dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: ^1.10.6
  test: ^1.15.5
  faker: ^1.3.0
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: pt_BR