name: clean_flutter_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  domain:
    path: ./domain
  logger: ^0.9.4
  hive: ^1.4.4+1
  provider: ^4.3.2+2
  enum_to_string: ^1.0.14
  path_provider: ^1.6.24
  rxdart: ^0.24.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: ^1.10.6
  test: ^1.15.5
  faker: ^1.3.0
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true